package codes.olmsted.michael.model

import dev.fritz2.lenses.Lenses

@Lenses
data class Experience(
    val id: Long,
    val startYear: Int,
    val endYear: Int?,
    val name: String,
    val title: String,
    val route: String,
    val summary: String,
    val category: Category,
    val skills: Set<Skill>,
    val topics: Set<Topic>,
    val iconUri: String,
    val imageUris: List<String>,
)

val STUB_EXPERIENCES: List<Experience> = listOf(
    Experience(
        id = 123,
        startYear = 2019,
        endYear = null,
        name = "StockX",
        title = "Android Software Engineer II",
        route = "/stockx",
        summary = "Developing a native Android application in Kotlin using Jetpack Compose, MVVM, Coroutines, Flow, and Clean Architecture. Working in a legacy Java codebase and introducing new features in Kotlin. Involved in checkout, payment, and internationalization feature work.",
        category = Category.JOB,
        skills = setOf(
            Skill.ANDROID,
            Skill.KOTLIN,
            Skill.JAVA,
            Skill.GRAPHQL,
        ),
        topics = setOf(
            Topic.E_COMMERCE,
            Topic.UI,
        ),
        iconUri = "/experiences/job/stockx/icon.jpeg",
        imageUris = listOf(
            "/job/stockx/load_regions.gif",
            "/job/stockx/sales_graph.gif",
            "/job/stockx/product_transition.gif",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2021,
        endYear = 2022,
        name = "a.team - McGraw Hill",
        title = "Android Developer",
        route = "/a_team/mcgraw_hill",
        summary = "Built a native Android app using Jetpack Compose, Coroutines, Flow, Hilt, Room, and GraphQL. Delivered a minimum viable direct-to-consumer product for the world's leading ed-tech company.",
        category = Category.FREELANCE,
        skills = setOf(
            Skill.ANDROID,
            Skill.KOTLIN,
            Skill.JAVA,
            Skill.GRAPHQL,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/freelance/ateam/icon.svg",
        imageUris = listOf(
            "/freelance/ateam/nda.png"
        ),
    ),
    Experience(
        id = 1234,
        startYear = 2018,
        endYear = 2019,
        name = "Trove",
        title = "Android Engineering Intern",
        route = "/trove",
        summary = "Developed a native Android application in Kotlin using RxJava with a Redux architecture. Focused on UI/UX implementation of features including reusable components, animations, and development of a platform style guide.",
        category = Category.JOB,
        skills = setOf(
            Skill.ANDROID,
            Skill.KOTLIN,
            Skill.JAVA,
        ),
        topics = setOf(
            Topic.CHAT,
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/job/trove/icon.jpeg",
        imageUris = listOf(
            "/job/trove/login.gif",
            "/job/trove/post.gif",
            "/job/trove/search.gif",
            "/job/trove/chat.png",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2019,
        endYear = 2019,
        name = "handotate",
        title = "Native Android & UI/UX Design",
        route = "/handotate",
        summary = "Used mvRx library from AirBnb to facilitate rapid iteration, created custom UI for annotating ML training datasets.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.ANDROID,
            Skill.KOTLIN,
            Skill.SQL,
            Skill.AWS,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/handotate/icon.png",
        imageUris = listOf(
            "/project/handotate/home.png",
            "/project/handotate/find.png",
            "/project/handotate/account.png",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2019,
        endYear = 2019,
        name = "Meet^",
        title = "React Native Android/iOS & UI/UX Design",
        route = "/meet_up",
        summary = "Used React Native and Firebase to build a realtime chat app for making spontaneous plans with friends.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.REACT_NATIVE,
            Skill.FIREBASE,
            Skill.JAVASCRIPT,
            Skill.NODEJS,
        ),
        topics = setOf(
            Topic.CHAT,
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/meet_up/icon.png",
        imageUris = listOf(
            "/project/meet_up/events.png",
            "/project/meet_up/groups.png",
            "/project/meet_up/chat.png",
        ),
    ),
    Experience(
        id = 77,
        startYear = 2018,
        endYear = 2018,
        name = "LineLeap Tickets",
        title = "React Web & UI/UX Design",
        route = "/lineleap",
        summary = "Integrated with Squarespace orders API to allow event staff to validate a user's digital ticket purchase.",
        category = Category.FREELANCE,
        skills = setOf(
            Skill.REACT,
            Skill.JAVASCRIPT,
            Skill.AWS,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/freelance/lineleap/icon.png",
        imageUris = listOf(
            "/freelance/lineleap/loading.png",
            "/freelance/lineleap/confirmed.png",
            "/freelance/lineleap/denied.png",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2018,
        endYear = 2018,
        name = "TaskTracker",
        title = "React Web & UI/UX Design",
        route = "/task_tracker",
        summary = "Focused on the product design of a Kanban style homework tracking web app. Built out the proper infrastructure to allow for user testing to validate MVP.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.REACT,
            Skill.JAVASCRIPT,
            Skill.AWS,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/task_tracker/icon.png",
        imageUris = listOf(
            "/project/task_tracker/classes.png",
            "/project/task_tracker/class.png",
            "/project/task_tracker/assignments.png",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2017,
        endYear = 2018,
        name = "Totem",
        title = "Native Android & UI/UX Design",
        route = "/totem",
        summary = "Developed a native Android application in Kotlin using RxJava and Dagger. Also responsible for the UI design, API design, and overall technology management of the company.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.ANDROID,
            Skill.KOTLIN,
            Skill.AWS,
            Skill.FIREBASE,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/totem/icon.png",
        imageUris = listOf(
            "/project/totem/private_feed.png",
            "/project/totem/public_feed.png",
            "/project/totem/refactor.png",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2017,
        endYear = 2017,
        name = "Present VR Advertising",
        title = "Unity & node.js",
        route = "/present",
        summary = "Created an SDK for Unity to allow for dynamic insertion of gamified ad experiences within any given VR experience.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.UNITY,
            Skill.NODEJS,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/present/icon.png",
        imageUris = listOf(
            "/project/present/user_test.png",
            "/project/present/pitch.jpg",
            "/project/present/presentation.jpg",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2017,
        endYear = 2017,
        name = "ARTabletop",
        title = "Unity & Android ARCore",
        route = "/artabletop",
        summary = "Built the backend to allow for realtime remote D&D gameplay through a shared interactive AR game board.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.UNITY,
            Skill.ARCORE,
            Skill.NODEJS,
            Skill.AWS,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/artabletop/icon.png",
        imageUris = listOf(
            "/project/artabletop/move_range.jpg",
            "/project/artabletop/tabletop.jpg",
            "/project/artabletop/up_close.jpg",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2016,
        endYear = 2017,
        name = "mFrame",
        title = "A-Frame WebVR & HTML",
        route = "/mframe",
        summary = "Built the backend for a web-based VR social network, where users could customize a virtual space to express themselves.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.HTML,
            Skill.NODEJS,
            Skill.AWS,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/mframe/icon.png",
        imageUris = listOf(
            "/project/mframe/vaporwave.png",
            "/project/mframe/vr.png",
            "/project/mframe/web.png",
        ),
    ),
    Experience(
        id = 12345,
        startYear = 2015,
        endYear = 2016,
        name = "GBHS",
        title = "Native Android & Native iOS",
        route = "/gbhs",
        summary = "Commissioned by the school to build a self-serve school resource app that scraped data from the official website.",
        category = Category.PROJECT,
        skills = setOf(
            Skill.ANDROID,
            Skill.JAVA,
            Skill.IOS,
            Skill.OBJECTIVE_C,
        ),
        topics = setOf(
            Topic.UI,
            Topic.UX,
        ),
        iconUri = "/experiences/project/gbhs/icon.png",
        imageUris = listOf(
            "/project/gbhs/drawer.png",
            "/project/gbhs/schedule.png",
            "/project/gbhs/calendar.png",
        ),
    ),
)
