package codes.miley.model

enum class Skill(val displayName: String) {
    ANDROID("Android"),
    ARCORE("ARCore"),
    AWS("AWS"),
    COMPOSE("Compose"),
    FIREBASE("Firebase"),
    GRAPHQL("GraphQL"),
    HTML("HTML"),
    IOS("iOS"),
    JAVA("Java"),
    JAVASCRIPT("Javascript"),
    JNI("JNI"),
    KOTLIN("Kotlin"),
    KOTLIN_MULTIPLATFORM("Kotlin Multiplatform"),
    NODEJS("node.js"),
    OBJECTIVE_C("Objective-C"),
    PROTOBUF("Protobuf"),
    REACT("React"),
    REACT_NATIVE("React Native"),
    SDK("SDK"),
    SQL("SQL"),
    SWIFT_UI("SwiftUI"),
    UNITY("Unity"),
}
